config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :invoices
  resources :projects, except: [:show]

  get 'portfolio/:id', to: "projects#show", as: :portfolio_project

  get 'portfolio', to: "pages#portfolio"
  get 'contact', to: "pages#contact"
  get 'cv', to: "pages#cv"

  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  delete 'logout', to: "sessions#destroy", as: :logout

  root "pages#index"
end

app/models/invoice.rb
class Invoice < ApplicationRecord

  Currencies = %w( CZK USD EUR )

  has_many :service_items, dependent: :destroy
  has_many :expense_items, dependent: :destroy

  belongs_to :client

  accepts_nested_attributes_for :service_items, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :expense_items, reject_if: :all_blank, allow_destroy: true

  before_validation :set_number!

  validates :date, presence: true
  validates :period_covered_from, presence: true
  validates :period_covered_to, presence: true
  validates :number, uniqueness: true

  validate :credit_note_price_not_positive

  before_save :ensure_due_date!
  before_save :ensure_currency!

  scope :published, -> { where(published: true) }
  scope :unpublished, -> { where.not(published: true) }
  scope :by_date, -> { order(date: :desc) }

  def in_currency(cur)
    convert_currency(self.price, self.currency, cur)
  end

  def save
    readonly! if was_published?
    super
  end

  private

  def was_published?
    published_was
  end

  def credit_note_price_not_positive
    total_price!
    if credit_note? && price > 0
      error = 'Credit Notes Should not have a Positive Price!'
      errors.add(:base, error)
    end
  end

  def convert_currency(amount, from, to)
    rates = { eur_usd: 1.14, eur_czk: 27.78, eur_eur: 1, usd_eur: 0.88, usd_czk: 24.31, usd_usd: 1, czk_eur: 0.036, czk_usd: 0.041, czk_czk: 1 }
    amount * rates["#{from}_#{to}".downcase.to_sym]
  end

  def total_price!
    sum = (service_items + expense_items).inject(0) { |s, item|
      s + convert_currency(item.price, item.currency, currency)
    }
    self.price = sum
  end

  def ensure_due_date!
    if due_date.blank?
      self.due_date = date + (credit_note? ? 0 : 30)
    end
  end

  def ensure_currency!
    self.currency = Currencies.first if currency.blank?
  end

  def ensure_invoice_year!
    self.invoice_year = date.year if date.present? && invoice_year.blank?
  end

  def ensure_invoice_count!
    return if invoice_count.present? || errors.any?

    last_invoice_count = Invoice
      .where(invoice_year: invoice_year)
      .where(client_id: client_id)
      .where.not(id: id)
      .order(:invoice_count)
      .pluck(:invoice_count)
      .last

    self.invoice_count = last_invoice_count.to_i + 1
  end

  def set_client_code!
    self.client_code = client.code
  end

  def set_number!
    set_client_code!  
    ensure_invoice_year! 
    ensure_invoice_count!

    count = invoice_count.to_s.rjust(3, '0')
    num = "#{client_code}-#{invoice_year}-#{count}"
    num = num.prepend('CN-') if credit_note?

    self.number = num
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < AdminController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @published = Invoice.published.by_date
    @unpublished = Invoice.unpublished.by_date
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
    respond_to do |f|
      f.html {}
      f.pdf do
        if @invoice.published?
          render pdf: @invoice.number, show_as_html: false, layout: 'pdf.html.erb', footer: { html: { template: 'invoices/_invoice_footer.pdf.erb' } }, disposition: 'attachment'
        else
          render pdf: @invoice.number, show_as_html: true, layout: 'pdf.html.erb', footer: { html: { template: 'invoices/_invoice_footer.pdf.erb' } }
        end
      end
    end
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
    @invoice.credit_note = true if params[:credit_note] == '1'
  end

  # GET /invoices/1/edit
  def edit
    redirect_to action: :index if @invoice.published?
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:credit_note, :number, :invoice_year, :invoice_count, :date, :due_date, :period_covered_from, :period_covered_to, :price, :client_id, :client_code, :published, :currency, service_items_attributes: [:id, :title, :description, :price, :currency, :_destroy], expense_items_attributes: [:id, :title, :description, :price, :currency, :_destroy])
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper

  def address_for(client)
    tag.p do 
      [
        client.name,
        client.address1, 
        client.address2, 
        city_state_zip_line(client),
        client.country,
        client.registration_no,
        client.tax_no
      ]
        .select {|attr| !attr.blank? }.each do |line|
          concat line
          concat '<br>'.html_safe
        end
    end
  end

  def city_state_zip_line(client)
    [:city,:state,:zip].map { |atrb| 
      if client.__send__(atrb).present?
        tag.span client.__send__(atrb) 
      end
    }.compact.join(', ').html_safe
  end
end

app/views/invoices/_expense_item_fields.html.erb
<div class="nested-fields">
  <%= f.text_field :title %>
  <%= f.text_area :description %>
  <div class="row">
    <div class="small-6 columns">
      <%= f.number_field :price, step: 'any' %>
    </div>
    <div class="small-6 columns">
      <%= f.select :currency, Invoice::Currencies %>
    </div>
  </div>
</div>

app/views/invoices/_form.html.erb
<%= form_with(model: @invoice) do |f| %>
  <%= f.hidden_field :credit_note %>
  <div class="row">
    <div class="small-9 columns">
      <%= f.collection_select :client_id, Client.all, :id, :name %>
    </div>
    <div class="small-3 columns">
      <%= f.select :currency, Invoice::Currencies %>
    </div>
  </div>
  <% unless params[:action] == 'new' %>
    <div class="row">
      <div class="small-6 columns">
        <%= f.number_field :invoice_year %>
      </div>
      <div class="small-6 columns">
        <%= f.number_field :invoice_count %>
      </div>
    </div>
  <% end %>
  <div class="row">
    <div class="small-6 columns">
      <%= f.date_field :date %>
    </div>
    <div class="small-6 columns">
      <%= f.date_field :due_date %>
    </div>
  </div>
  <div class="row">
    <div class="small-6 columns">
      <%= f.date_field :period_covered_from %>
    </div>
    <div class="small-6 columns">
      <%= f.date_field :period_covered_to %>
    </div>
  </div>
  <h3>Services</h3>
  <div id="service_items">
    <%= f.fields_for :service_items do |s| %>
      <%= render 'service_item_fields', f: s %>
    <% end %>
    <%= link_to_add_association '+ Add a Service', f, :service_items %>
  <h3>Expenses</h3>
  <div id="expense_items">
    <%= f.fields_for :expense_items do |e| %>
      <%= render 'expense_item_fields', f: e %>
    <% end %>
    <%= link_to_add_association '+ Add an Expense', f, :expense_items %>
  </div>
  <div class="clearfix"></div>
  <br>
  <%= f.check_box :published, hint: "If you publish an Invoice, you will not be able to edit it" %>
  <div class="clearfix"></div>
  <br>
  <%= f.submit %>
  <div class="clearfix"></div>
<% end %>

app/views/invoices/_invoice_footer.pdf.erb
<footer class="text-center">
  <p class="office-address">
    John Hager - U Krčské Vodárny 5, 140 00 Prague 4, Czech Republic
  </p>
</footer>

app/views/invoices/_invoice_item_type.pdf.erb
<table class="invoice-items no-style">
  <thead>
    <th><%= items.first.human_name %></th>
    <th>Price</th>
  </thead>
  <tbody>
    <% items.each do |item| %>
      <tr>
        <td>
          <h6><%= item.title %></h6>
          <p>
            <em>Description: <%= item.description || 'N/A' %></em>
          </p>
        </td>
        <td>
          <%= number_to_currency(item.price, unit: item.currency) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/invoices/_invoices.html.erb
<% published = invoices.first.published? %>
<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Date</th>
      <th>Due date</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.number %></td>
        <td><%= invoice.date.strftime('%d-%m-%Y') %></td>
        <td><%= invoice.due_date.strftime('%d-%m-%Y') %></td>
        <td><%= number_to_currency(invoice.price, unit: invoice.currency) %></td>
        <% if published %>
          <td><%= link_to 'Download', invoice_path(id: invoice.id, format: :pdf) %></td>
        <% else %>
          <td><%= link_to 'Show', invoice %></td>
          <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
        <% end %>
        <td><%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/invoices/_service_item_fields.html.erb
<div class="nested-fields">
  <%= f.text_field :title %>
  <%= f.text_area :description %>
  <div class="row">
    <div class="small-6 columns">
      <%= f.number_field :price, step: 'any' %>
    </div>
    <div class="small-6 columns">
      <%= f.select :currency, Invoice::Currencies %>
    </div>
  </div>
</div>

app/views/invoices/edit.html.erb
<h1>Editing invoice</h1>

<%= render 'form' %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/index.html.erb
<h1>Listing invoices</h1>

<h2>Editables</h2>
<%= link_to '+ New Invoice', new_invoice_path %>
<%= link_to '+ New Credit Note', new_invoice_path(credit_note: 1) %>
<br>
<br>
<%= render 'invoices', invoices: @unpublished unless @unpublished.empty? %>
<h2>Published</h2>
<%= render 'invoices', invoices: @published unless @published.empty? %>

app/views/invoices/new.html.erb
<% if @invoice.credit_note? %>
  <h1>New credit note</h1>
<% else %>
  <h1>New invoice</h1>
<% end %>

<%= render 'form' %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @invoice.number %></h1>
<div class="row">
  <div class="small-6 columns">
    <p>
      <strong>Date:</strong>
      <%= @invoice.date %>
    </p>
  </div>
  <div class="small-6 columns">
    <p>
      <strong>Due date:</strong>
      <%= @invoice.due_date %>
    </p>
  </div>
  <div class="small-6 columns">
    <p>
      <strong>Period covered from:</strong>
      <%= @invoice.period_covered_from %>
    </p>
  </div>
  <div class="small-6 columns">
    <p>
      <strong>Period covered to:</strong>
      <%= @invoice.period_covered_to %>
    </p>
  </div>
</div>
<div class="row">
  <div class="small-6 columns small-offset-6">
    <p>
      <strong>Price:</strong>
      <%= @invoice.price %>
    </p>
  </div>
</div>

<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Preview', invoice_path(format: :pdf) %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/show.pdf.erb
<% content_for(:title, @invoice.number) %>
<div class="row">
  <div class="small-6 columns text-left">
    <h2>John Hager</h2>
    <p>
      U Krčské vodárny 428/5<br>
      140 00 Prague 4<br>
      Czech Republic<br>
      IČO: 02461340<br>
      DIČ: CZ683366505
    </p>
    <strong>Client Info: </strong>
    <%= address_for(@invoice.client) %>
  </div>
  <div class="small-6 columns text-right">
    <% if @invoice.published? %>
      <%= wicked_pdf_image_tag('jh-logo-blk.png', class: 'pdf-logo') %>
    <% else %>
      <%= image_tag('jh-logo-blk.png', class: 'pdf-logo') %>
    <% end %>
  </div>
</div>
<div class="row">
  <table id="invoiceInfo" class="no-style">
    <thead></thead>
    <tbody>
      <tr>
        <td>Invoice Date:</td>
        <td><%= @invoice.date.strftime('%d-%m-%Y') %></td>
      </tr>
      <tr>
        <td>Invoice No.:</td>
        <td><%= @invoice.number %></td>
      </tr>
      <tr>
        <td>Payment Due:</td>
        <td><%= @invoice.due_date.strftime('%d-%m-%Y') %></td>
        <td>Period Covered:</td>
        <td><%= @invoice.period_covered_from.strftime('%d-%m-%Y') %></td>
        <td> to </td>
        <td><%= @invoice.period_covered_to.strftime('%d-%m-%Y') %></td>
      </tr>
    </tbody>
  </table>
</div>
<div class="row">
  <%= render 'invoice_item_type', items: @invoice.service_items if @invoice.service_items.present? %>
</div>
<div class="row">
  <%= render 'invoice_item_type', items: @invoice.expense_items if @invoice.expense_items.present? %>
</div>
<div class="row">
  <table class="total-row no-style">
    <tr>
      <th>Total</th>
      <td>
        <%= number_to_currency(@invoice.price, unit: @invoice.currency) %>
      </td>
    </tr>
  </table>
</div>
<div class="row">
  <br>
  <br>
  <p>
    <% if @invoice.credit_note? %>
      This credit note takes immediate affect from <%= @invoice.due_date.strftime('%d-%m-%Y') %>.
    <% else %>
      We kindly ask you to remit the total above, in <%= @invoice.currency %>, within 30 days of the invoice date. Payments made after this period may be subject to penalty.
    <% end %>
  </p>
</div>
<div class="row">
  <div class="small-12 columns">
    <h4>Payment Details:</h4>
  </div>
  <div class="small-8 columns small-offset-2 end">
    <table id="paymentDetails" class="no-style">
      <tr>
        <td>Account Holder:</td>
        <td>John Hager</td>
      </tr>
      <tr>
        <td>IBAN:</td>
        <td>CZ06 6210 6701 0022 1111 2298</td>
      </tr>
      <tr>
        <td>Address:</td>
        <td>U Krčské vodárny 428/5</td>
      </tr>
      <tr>
        <td></td>
        <td>140 00 Prague 4</td>
      </tr>
      <tr>
        <td></td>
        <td>Czech Republic</td>
      </tr>
      <tr>
        <td>BIC/SWIFT:</td>
        <td>BREXCZPP</td>
      </tr>
      <tr>
        <td>Bank:</td>
        <td>mBank</td>
      </tr>
    </table>
  </div>
</div>