config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :invoices
  resources :projects, except: [:show]

  get 'portfolio/:id', to: "projects#show", as: :portfolio_project

  get 'portfolio', to: "pages#portfolio"
  get 'contact', to: "pages#contact"
  get 'cv', to: "pages#cv"

  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  delete 'logout', to: "sessions#destroy", as: :logout

  root "pages#index"
end

app/models/project.rb
class Project < ApplicationRecord

  scope :by_updated, -> { order(updated_at: :desc) }

  def image
    name.underscore.parameterize.underscore + ".jpg"
  end
end

app/controllers/projects_controller.rb
class ProjectsController < AdminController

  skip_before_action :authenticate_user, only: [:show]
  before_action :set_project, except: [:index, :new, :create]

  layout 'application', only: [:show]


  def index
    @projects = Project.by_updated
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.create(project_params)
    redirect_to action: :index
  end

  def show
    respond_to do |f|
      f.html {}
      f.pdf do
        render pdf: @project.name, layout: 'pdf.html.erb', disposition: 'attachment'
      end
    end
  end

  def edit
  end

  def update
    @project.update(project_params)
    redirect_to action: :index
  end

  def destroy
    @project.destroy
    redirect_to action: :index
  end

  private
  def project_params
    params.require(:project).permit(:name, :url, :description)
  end

  def set_project
    @project = Project.find(params[:id])
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: @project, html: {class: "basic_form"}) do |f| %>
  <%= f.text_field :name %>
  <br>
  <%= f.url_field :url %>
  <br>
  <%= f.text_area :description %>
  <%= f.submit %>  
<% end %>

app/views/projects/_project.html.erb
<li>
  <%= link_to project.url, target: "_blank" do %>
    <%= image_tag project.image, class: 'full-image' %>
  <% end %>
  <h6 class="subheader">
    <%= link_to project.name, portfolio_project_path(project) %>
  </h6>
  <p>
    <%= project.description %>
  </p>
</li>

app/views/projects/_project.pdf.erb
<article>
  <h1 class="code"><%= @project.name %></h1>
  <section class="text-center">
    <%= link_to @project.url, target: "_blank" do %>
      <%= wicked_pdf_image_tag @project.image %>
    <% end %>
    <p><%= @project.description %></p>
  </section>
</article>

app/views/projects/edit.html.erb
<section>
  <%= form_tag url: {action: :create}, html: {class: "project_form"} do %>
    <%= label_tag :name, 'Name: ' %>
    <%= text_field_tag :name, @project.name %>
    <br>
    <%= label_tag :purl, 'URL: ' %>
    <%= text_field_tag :purl, @project.url %>
    <br>
    <%= label_tag :description, 'Description: ' %>
    <br>
    <%= text_area_tag :description, @project.description %>
    <%= submit_tag "SAVE" %>
  <% end %>
</section>

app/views/projects/index.html.erb
<section>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Project URL</th>
        <th>Last Updated</th>
        <th colspan="4"></th>
      </tr>
    </thead>
    <tbody>
      <% @projects.each do |project| %>
        <tr>
          <td><%= project.name %></td>
          <td><%= link_to project.url, project.url %></td>
          <td><%= project.updated_at %></td>
          <td><%= link_to "Download", project_path(project, format: :pdf) %></td>
          <td><%= link_to "Edit", edit_project_path(project) %></td>
          <td><%= link_to "Destroy", project, method: :delete, data: { confirm: "Are you sure?" } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to "+ New project", new_project_path %>
</section>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/read.html.erb
<article>
  <header>
    <h1><%= @project.name %></h1>
  </header>
<section class="centered">
  <%= link_to @project.url, target: "_blank" do %>
    <%= image_tag @project.image %>
  <% end %>
  <p><%= @project.description %></p>
</section>

app/views/projects/read.pdf.erb
<% content_for(:title, @project.name) %>
<%= render @project %>

app/views/projects/show.html.erb
<article>
  <header>
    <h1><%= @project.name %></h1>
  </header>
  <section class="centered">
    <%= link_to @project.url, target: "_blank" do %>
      <%= image_tag @project.image %>
    <% end %>
    <p><%= @project.description %></p>
  </section>
</article>

app/views/projects/show.pdf.erb
<% content_for(:title, @project.name) %>
<%= render @project %>