config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :invoices
  resources :projects, except: [:show]

  get 'portfolio/:id', to: "projects#show", as: :portfolio_project

  get 'portfolio', to: "pages#portfolio"
  get 'contact', to: "pages#contact"
  get 'cv', to: "pages#cv"

  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  delete 'logout', to: "sessions#destroy", as: :logout

  root "pages#index"
end

app/views/layouts/_admin_links.html.erb
<li class="divider hide-for-medium"></li>
<li><%= link_to "Clients", clients_path %></li>
<li class="divider hide-for-medium"></li>
<li><%= link_to "Invoices", invoices_path %></li>
<li class="divider hide-for-medium"></li>
<li><%= link_to "Projects", projects_path %></li>
<li class="divider hide-for-medium"></li>
<li>
  <%= link_to "Logout", logout_path, method: "delete" %>
</li>

app/views/layouts/_cv.html.erb
<header>
  <h1>Curriculum Vitae</h1>
</header>

<section>
  <%= render 'layouts/cv/skills' %>
  <%= render 'layouts/cv/languages' %>
  <%= render 'layouts/cv/projects' %>
  <%= render 'layouts/cv/experience' %>
  <%= render 'layouts/cv/education' %>
  <%= render 'layouts/cv/independent' %>
  <%= render 'layouts/cv/volunteer' %>
  <%= render 'layouts/cv/interest' %>
</section>

app/views/layouts/_github_side.html.erb
<div class="large-4 columns">
  <section>
    <h2>Contact John</h2>
    <p>
      You can look for me as @jphager2 almost anywhere. 
      If you can't find me there, just 
      <%= mail_to "jh@john-hager.info", "send me an email" %>
      .
    </p>
  </section>

  <section>
    <h2>Github Activity</h2>
    
    <div class="row">
      <div class="large-12 columns">
        
        <table>
          <thead>
          </thead>
          <tbody id="githubActivity">
            <% @events.each do |event| %>
              <tr>
                <td class="code">
                  <%= link_to event.uri, target: "_blank" do %> 
                    <div>
                      On <%= event.datetime %>,
                      <span class="red">John</span>:
                      <span class="yellow"><%= event.action %></span>
                      =&gt;<br>
                      <span class="green"><%= event.repo %></span>
                      <br>
                      <blockquote>
                        <%= event.message %>
                      </blockquote>
                    </div>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        
        <%= image_tag @events.first.profile_img, class: "profile" %>
        <h6 class="subheader">@jphager2</h6>

    </div>
  </section>
</div>

app/views/layouts/_head.html.erb
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title><%= content_for?(:title) ? yield(:title) : "John Hager" %></title>

  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag "favicon.ico" %>

  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-50971654-1', 'john-hager.info');
    ga('send', 'pageview');

  </script>
</head>

app/views/layouts/_icon_credits.html.erb
<p>
  I have to thank these nice people who made their work available for
  free. Excellent stuff. Thanks so much!
</p>
<ul class="no-bullet fine-print">
  <li><div>Icon made by Stephen Hutchings from <a href="http://www.flaticon.com" title="Flaticon">www.flaticon.com</a>         is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0">CC BY 3.0</a></div></li>

  <li><div>Icon made by <a href="http://www.simpleicon.com" title="SimpleIcon">SimpleIcon</a> from <a href="http://www.flaticon.com" title="Flaticon">www.flaticon.com</a> is licensed under <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0">CC BY 3.0</a></div></li>

  <li><div>Icon made by <a href="http://www.elegantthemes.com" title="Elegant Themes">Elegant Themes</a> from <a href="http://www.flaticon.com" title="Flaticon">www.flaticon.com</a> is licensed under <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0">CC BY 3.0</a></div></li>

  <li><div>Icon made by <a href="http://www.freepik.com" title="Freepik">Freepik</a> from <a href="http://www.flaticon.com" title="Flaticon">www.flaticon.com</a> is licensed under <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0">CC BY 3.0</a></div></li>

  <li><div>Icon made by <a href="http://www.icomoon.io" title="Icomoon">Icomoon</a> from <a href="http://www.flaticon.com" title="Flaticon">www.flaticon.com</a> is licensed under <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0">CC BY 3.0</a></div></li>

  <li><div>Icon made by <a href="http://yanlu.de" title="Yannick">Yannick</a> from <a href="http://www.flaticon.com" title="Flaticon">www.flaticon.com</a> is licensed under <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0">CC BY 3.0</a></div></li>
</ul>

app/views/layouts/_nav.html.erb
<div class="row">
  <div class="large-12 columns">
    <div class="sticky fixed">
      <nav class="top-bar" data-topbar="">
        <ul class="title-area">
          <!-- Title Area -->
          <li class="name">
            <%= link_to root_path, class: "name logo" do %>
              <h1>John Hager</h1>
              <%= image_tag "jh-logo.png" %>
            <% end %>         
          </li>
          <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
          <li class="toggle-topbar menu-icon">
            <a href="#"></a>
          </li>
        </ul>


        <section class="top-bar-section">

          <!-- Right Nav Section -->
          <ul class="right">
            <li class="divider hide-for-medium"></li>
            <li><%= link_to "Home", root_path %></li>
            <li class="divider hide-for-medium"></li>
            <li><%= link_to "Portfolio", 'portfolio'%></li>
            <li class="divider hide-for-medium"></li>
            <li><%= link_to "CV", 'cv' %></li>
            <li class="divider hide-for-medium"></li>
            <li><%= link_to "Contact", 'contact' %></li>
            <li class="divider hide-for-medium"></li>
            <li><%= link_to "Feedback", 'https://github.com/jphager2/john-hager-info/issues', target: "_blank" %></li>
            <% if signed_in? %>
              <%= render 'layouts/admin_links' %>
            <% else %>
              <li class="divider hide-for-medium"></li>
              <li><%= link_to "Login", "/login" %></li>
            <% end %>
          </ul>
        </section>
      </nav>
    </div>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <%= render 'layouts/head' %>
  <body>
    <%= render 'layouts/nav' %>
      
    <div class="row">
      <div class="small-12 columns">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <%= render 'layouts/head' %>
  <body>
    <%= render 'layouts/nav' %>
    
    <div class="row">
      <div class="large-8 columns">
        <%= yield %>
      </div>
      <%= render 'layouts/github_side' %>

    </div>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>John Hager Info<%= " | #{yield(:title)}" if content_for?(:title) %></title>
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
  <%= wicked_pdf_stylesheet_link_tag("application").gsub(/url\("\//, "url(\"file://#{Rails.root}/").html_safe %>
  <style>
    .code, h1, h2, h3, h4, h5, h6 {
      font-family: "Liberation Mono", Courier, monospace;
    }
  </style>

</head>
<body class="pdf-body">
  <%= yield %> 
</body>
</html>